### PR TITLE
Fix image painting when rotate !== 0

### LINKED ISSUE #183: Image Positioning on Rotate
Thank you for implementing image rotating (#175). I'm seeing some odd behavior in the demo, however. It looks like the canvas is rotated as well as the image. This is easy to resolve with swapping height and width on 90 degree rotate. 

The image position is not as expected. On rotate the image is outside of the canvas. Scaling and panning can get it part of the way into the crop area, but there is something preventing the image from filling the canvas. In the screenshots, the whitespace in the canvas reflects the point at which you cannot pan more. It appears to be rotating from the top left origin, which is normal in rotate. Would x and y position need to be adjusted on rotate to keep the center of the image positioned in the center canvas?

screen shot 2017-07-13 at 8 36 22 am

screen shot 2017-07-13 at 8 40 35 am

### PR DESCRIPTION
**Pull request by mtlewis**
Previously the canvas was scaled before applying the rotation, but the transform origin did not take account of the scaling, which meant that the image was not rotated around its center, causing it to ping off somewhere else off-canvas.  Now, the scale factor is applied after the transform, so there's no need to account for it.

Fixes #183.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -236,7 +236,7 @@ class AvatarEditor extends React.Component {
     }
 
     // don't paint a border here, as it is the resulting image
-    this.paintImage(canvas.getContext('2d'), this.state.image, 0)
+    this.paintImage(canvas.getContext('2d'), this.state.image, 0, 1)
```
Comment (mtlewis) [inline src/index.js]: Because scaling is now built into `paintImage`, we need to override it here so that getImageScaledToCanvas doesn't start outputting an image of a different size.  We could consider whether the image *should* be larger for HiDPI devices, but I'd suggest we think about that as a separate change.

**Comment by mosch** [comment]
awesome!
